sudo: required
services: -docker

before_install:
  - docker build -t nadireaziz/simplereact -f Dockerfile.dev .
script:
  - docker run -e CI=true nadireaziz/simplereact npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "simplereact"
  env: "Simplereact-env"
  bucket_name: "elasticbeanstalk-us-east-1-634696999570"
  bucket_path: "simplereact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
